# Generated by Django 5.0.2 on 2024-04-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_phone_number', models.CharField(max_length=20, verbose_name='Main Phone Number')),
                ('main_address', models.CharField(max_length=100, verbose_name='Main Address')),
                ('main_email_address', models.EmailField(max_length=254, verbose_name='Main Email Address')),
                ('main_home_greeting_text', models.TextField(verbose_name='Main Home Greeting Text')),
                ('main_home_greeting_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_home_greeting_image', to='media.media', verbose_name='Main Home Greeting Image')),
                ('our_blog_page_back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_blog_page_back_image', to='media.media', verbose_name='Our Blog Page Back Image')),
                ('related_products_back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_back_image', to='media.media', verbose_name='Related Products Back Image')),
                ('you_may_be_interested_in_page_back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='you_may_be_interested_in_page_back_image', to='media.media', verbose_name='You May Be Interested In Page Back Image')),
            ],
            options={
                'verbose_name': 'Common Settings',
                'verbose_name_plural': 'Common Settings',
            },
        ),
    ]
